language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "JuE9XXqfZhRLmFYAXKJLoFJDAr36Q57nsLF63YrTv/3Ftc0UCOrIQwuLqUhGU+bOp8s17ZrpKZ62HDPQRRUMgSGYY3F0/KqvLkDuIpXLLnvRLVDLr+stUr0v7c8HVgh2hfXfrFS/vpIBrs22Z2gPIby4vtQd/gTR11cY4bddqEQ="
    on:
      tags: true
      all_branches: true
